install.packages("palmerpenguins")
install.packages("here")
require(palmerpenguins)
require(here)
penguins = data.frame(penguins)
mean(penguins$body_mass_g)
head(penguins)
mean(penguins)
summary(penguins)
plot(penguins$bill_length_mm, penguins$bill_depth_mm) #scatter
pairs(penguins) #pair plot
boxplot(penguins$bill_depth_mm)
boxplot(bill_depth_mm ~ sex, data = penguins)
par(mfrow = c(1, 2))
boxplot(penguins$bill_depth_mm)
boxplot(bill_depth_mm ~ sex, data = penguins)
dev.off()
coplot(body_mass_g ~ bill_length_mm | sex, data = penguins)
